### PR TITLE
Laravel 11.x Compatibility and Service Provider Refactoring

### PR DESCRIPTION
**Pull request by alissn**
Hi,

This pull request refactors the registration of service providers to ensure compatibility with Laravel 11.x. It includes adding a default service provider and preventing duplication of classes with the same logic.

```php
switch ($version) {
    case 4:
        return new ServiceProviderLaravel4($app);
        break;
    case 5:
        return new ServiceProviderLaravel5($app);
        break;
    default:
        return new ServiceProviderLaravelDefault($app);
}
```

If further description or clarification is needed, please let me know.

### CODE REVIEW

**Comment by ariaieboy** [comment]
cc:
@hosseinRezaei188

**Comment by alissn** [comment]
@hosseinRezaei188
Please release new version.

Thanks.

**Comment by kazemmdev** [comment]
@alissn, you can install it using the 'dev-master' tag until it is officially released.

**Comment by alissn** [comment]
@kazemmdev 

Thanks 🙏

**Comment by hosseinRezaei188** [comment]
The updated package was released.

**Pull request merged**
